# This build file heavily uses template features from YAML to help you in only
# changing a minimal part of it and avoid code duplication to a maximum while
# still providing a nice pipeline display on your package.


# CI instructions (only change if you know what you're doing)
# -------------------------------------------------------------------

# Definition of our build pipeline
stages:
  - build
  - test
  - docs
  - upload

# Global variables
variables:
  TEST_CHANNEL: file://idiap/group/torch5spro/bob_master_conda_channel

# Global caching
cache:
  key: "$CI_BUILD_REF_NAME" # per branch cache
  paths:
    - miniconda/

# Template for the build stage
# Needs to run on all supported architectures, platforms and python versions
.build_template: &build_job
  stage: build
  before_script:
    - git clean -ffdx
    - ./bootstrap-conda.sh miniconda ${PYTHON_VER}
  variables: &build_variables
    BOB_DOCUMENTATION_SERVER: "http://www.idiap.ch/software/bob/docs/latest/bob/%s/master/"
  script:
    - miniconda/bin/conda build --no-test --python=${PYTHON_VER} .conda-recipe
    - miniconda/bin/conda install -n root --yes ${CI_PROJECT_NAME}
    - miniconda/bin/sphinx-build doc sphinx
  artifacts:
    expire_in: 1 day
    paths:
      - miniconda/conda-bld/linux-64
      - miniconda/conda-bld/osx-64
      - sphinx/

# Template for building on a Linux machine
.build_linux_template: &linux_build_job
  <<: *build_job
  variables: &linux_build_variables
    <<: *build_variables
    CFLAGS: "-D_GLIBCXX_USE_CXX11_ABI=0 -coverage"
    CXXFLAGS: "-D_GLIBCXX_USE_CXX11_ABI=0 -coverage"
  tags:
    - conda-linux

# Template for building on a Mac OSX machine
.build_mac_template: &macosx_build_job
  <<: *build_job
  variables: &macosx_build_variables
    <<: *build_variables
    MACOSX_DEPLOYMENT_TARGET: "10.9"
    CFLAGS: "-pthread -coverage"
    CXXFLAGS: "-pthread -coverage"
    LDFLAGS: "-lpthread"
  tags:
    - conda-macosx


# Template for the test stage - re-install from uploaded wheels
# Needs to run on all supported architectures, platforms and python versions
.test_template: &test_job
  stage: test
  before_script:
    - mv miniconda miniconda_bak
    - ./bootstrap-conda.sh miniconda ${PYTHON_VER}
    - mv miniconda_bak/conda-bld miniconda/

.test_linux_template: &linux_test_job
  <<: *test_job
  script:
    - miniconda/bin/conda build --test miniconda/conda-bld/linux-64/${CI_PROJECT_NAME}-master-py*
  tags:
    - conda-linux

.test_mac_template: &mac_test_job
  <<: *test_job
  script:
    - miniconda/bin/conda build --test miniconda/conda-bld/osx-64/${CI_PROJECT_NAME}-master-py*
  tags:
    - conda-macosx

# Template for (latest) documentation upload stage
# Only one real job needs to do this
.docs_template: &docs_job
  stage: docs
  only:
    - master
  before_script:
    - curl --silent https://gitlab.idiap.ch/bob/bob/snippets/9/raw | tr -d '\r' > upload-sphinx.sh
    - chmod 755 upload-sphinx.sh
  script:
    - ./upload-sphinx.sh

.docs_linux_template: &linux_docs_job
  <<: *docs_job
  tags:
    - conda-linux

.docs_mac_template: &mac_docs_job
  <<: *test_job
  tags:
    - conda-macosx


# Template for the package uploading stage
# Needs to run against all combination of python and all supported
# architectures (Linux and Mac OSX 64-bit)
.upload_template: &upload_job
  stage: upload
  before_script:
    - ./bootstrap-conda.sh miniconda 2.7
  only:
    - conda-ci

.upload_linux_template: &linux_upload_job
  <<: *upload_job
  script:
    - rsync miniconda/conda-bld/linux-64 /idiap/group/torch5spro/bob_master_conda_channel
    - miniconda/bin/conda index /idiap/group/torch5spro/bob_master_conda_channel/linux-64
  tags:
    - conda-linux

.upload_mac_template: &macosx_upload_job
  <<: *upload_job
  script:
    - rsync miniconda/conda-bld/osx-64 /idiap/group/torch5spro/bob_master_conda_channel
    - miniconda/bin/conda index /idiap/group/torch5spro/bob_master_conda_channel/osx-64
  tags:
    - conda-macosx

# Different combinations. docs only happens in Python 3.5 and Linux
# -------------------------------------------------------------------

# Linux + Python 2.7: Build, test, and upload
build_linux_27:
  <<: *linux_build_job
  variables:
    <<: *linux_build_variables
    PYTHON_VER: "2.7"

test_linux_27:
  <<: *linux_test_job
  variables:
    <<: *linux_build_variables
    PYTHON_VER: "2.7"
  dependencies:
    - build_linux_27

upload_linux_27:
  <<: *linux_upload_job
  dependencies:
    - build_linux_27

# Linux + Python 3.4: Build, test, and upload
build_linux_34:
  <<: *linux_build_job
  variables:
    <<: *linux_build_variables
    PYTHON_VER: "3.4"

test_linux_34:
  <<: *linux_test_job
  variables:
    <<: *linux_build_variables
    PYTHON_VER: "3.4"
  dependencies:
    - build_linux_34

upload_linux_34:
  <<: *linux_upload_job
  dependencies:
    - build_linux_34

# Linux + Python 3.5: Build, test, docs, and upload
build_linux35:
  <<: *linux_build_job
  variables:
    <<: *linux_build_variables
    PYTHON_VER: "3.5"

test_linux35:
  <<: *linux_test_job
  variables:
    <<: *linux_build_variables
    PYTHON_VER: "3.5"
  dependencies:
    - build_linux35

docs_linux35:
  <<: *linux_docs_job
  dependencies:
    - build_linux35

upload_linux35:
  <<: *linux_upload_job
  dependencies:
    - build_linux35

# # MacOSX + Python 2.7: Build, test, and upload
# build_macosx_27:
#   <<: *macosx_build_job
#   variables:
#     <<: *macosx_build_variables
#     PYTHON_VER: "2.7"

# test_macosx_27:
#   <<: *mac_test_job
#   variables:
#     <<: *macosx_build_variables
#     PYTHON_VER: "2.7"
#   dependencies:
#     - build_macosx_27

# upload_macosx_27:
#   <<: *macosx_upload_job
#   dependencies:
#     - build_macosx_27

# # MacOSX + Python 3.4: Build, test, and upload
# build_macosx_34:
#   <<: *macosx_build_job
#   variables:
#     <<: *macosx_build_variables
#     PYTHON_VER: "3.4"

# test_macosx_34:
#   <<: *mac_test_job
#   variables:
#     <<: *macosx_build_variables
#     PYTHON_VER: "3.4"
#   dependencies:
#     - build_macosx_34

# upload_macosx_34:
#   <<: *macosx_upload_job
#   dependencies:
#     - build_macosx_34

# # MacOSX + Python 3.5: Build, test, and upload
# build_macosx35:
#   <<: *macosx_build_job
#   variables:
#     <<: *macosx_build_variables
#     PYTHON_VER: "3.5"

# test_macosx35:
#   <<: *mac_test_job
#   variables:
#     <<: *macosx_build_variables
#     PYTHON_VER: "3.5"
#   dependencies:
#     - build_macosx35

# upload_macosx35:
#   <<: *macosx_upload_job
#   dependencies:
#     - build_macosx35
