image: condaforge/linux-anvil

stages:
  - build
  - test

cache:
  key: "$CI_PROJECT_NAMESPACE/$CI_BUILD_NAME" # per group name and build name
  paths:
    - miniconda.sh

.build_template: &build_job
  stage: build
  before_script:
    - ./bootstrap-conda.sh miniconda ${PYTHON_VER}
  variables: &build_variables
    BOB_DOCUMENTATION_SERVER: "http://www.idiap.ch/software/bob/docs/latest/bob/%s/master/"
  script:
    - miniconda/bin/conda build --no-test --python=${PYTHON_VER} .conda-recipe
    - miniconda/bin/conda install -n root --yes ${CI_PROJECT_NAME}
    - miniconda/bin/sphinx-build doc sphinx
  artifacts:
    expire_in: 1 day
    paths:
      - miniconda/conda-bld/linux-64
      - miniconda/conda-bld/osx-64
      - sphinx/

# Template for building on a Linux machine
.build_linux_template: &linux_build_job
  <<: *build_job
  variables: &linux_build_variables
    <<: *build_variables
    CFLAGS: "-D_GLIBCXX_USE_CXX11_ABI=0 -coverage"
    CXXFLAGS: "-D_GLIBCXX_USE_CXX11_ABI=0 -coverage"
    LINUXMAC: linux-64

# Template for the test stage - re-install from uploaded wheels
# Needs to run on all supported architectures, platforms and python versions
.test_template: &test_job
  stage: test
  before_script:
    - mv miniconda miniconda_bak
    - ./bootstrap-conda.sh miniconda ${PYTHON_VER}
    - mv miniconda_bak/conda-bld miniconda/
  script:
    - miniconda/bin/conda build --test --python=${PYTHON_VER} miniconda/conda-bld/${LINUXMAC}/${CI_PROJECT_NAME}-master-py*

.test_linux_template: &linux_test_job
  <<: *test_job


# Linux + Python 3.5: Build, test
build_linux35:
  <<: *linux_build_job
  variables:
    <<: *linux_build_variables
    PYTHON_VER: "3.5"
  tags:
    - docker

test_linux35:
  <<: *linux_test_job
  variables:
    <<: *linux_build_variables
    PYTHON_VER: "3.5"
  dependencies:
    - build_linux35
  tags:
    - docker
