# This build file is defined in two parts: 1) a generic set of instructions you
# probably **don't** need to change and 2) a part you may have to tune to your
# project. It heavily uses template features from YAML to help you in only
# changing a minimal part of it and avoid code duplication to a maximum while
# still providing a nice pipeline display on your package.


# 1) Generic instructions (only change if you know what you're doing)
# -------------------------------------------------------------------

# Definition of our build pipeline
stages:
  - build
  - test
  - docs
  - wheels


# Global variables
variables:
  CONDA_PREFIX: build-dev


# Template for the build stage
# Needs to run on all supported architectures, platforms and python versions
.build_template: &build_job
  stage: build
  before_script:
    - git clean -ffdx
    - wget -O- https://gitlab.idiap.ch/bob/bob/snippets/7/raw | tr -d '\r' > bootstrap-conda.sh
    - chmod 755 ./bootstrap-conda.sh
    - ./bootstrap-conda.sh ${CONDA_FOLDER} ${PYTHON_VER} ${CONDA_PREFIX}
  variables: &build_variables
    BOB_DOCUMENTATION_SERVER: "http://www.idiap.ch/software/bob/docs/latest/bob/%s/master/"
  script:
    - ./bin/buildout
    - ./bin/sphinx-build -b html doc sphinx
  after_script:
    - rm -rf ${CONDA_PREFIX}
  artifacts:
    expire_in: 2 hours
    paths:
      - bootstrap-conda.sh
      - ${CI_PROJECT_NAME}.egg-info/
      - .installed.cfg
      - parts/
      - bin/
      - eggs/
      - develop-eggs/
      - sphinx/


# Template for building on a Linux machine
.build_linux_template: &linux_build_job
  <<: *build_job
  variables: &linux_build_variables
    <<: *build_variables
    CONDA_FOLDER: "/local/conda"


# Template for building on a Mac OSX machine
.build_mac_template: &macosx_build_job
  <<: *build_job
  variables: &macosx_build_variables
    <<: *build_variables
    CONDA_FOLDER: "/opt/conda"
    MACOSX_DEPLOYMENT_TARGET: "10.9"
    CFLAGS: "-pthread"


# Template for the test stage
# Needs to run on all supported architectures, platforms and python versions
.test_template: &test_job
  stage: test
  before_script:
    - ./bootstrap-conda.sh ${CONDA_FOLDER} ${PYTHON_VER} ${CONDA_PREFIX}
    - ./bin/buildout -o
  script:
    - ./bin/python -c 'from bob.extension import get_config; print(get_config())'
    - ./bin/coverage run --source=${CI_PROJECT_NAME} ./bin/nosetests -sv
    - ./bin/sphinx-build -b doctest doc sphinx
  after_script:
    - rm -rf ${CONDA_PREFIX}


# Template for testing on a Linux machine
.test_linux_template: &linux_test_job
  <<: *test_job
  variables:
    <<: *linux_build_variables


# Template for testing on a Mac OSX machine
.test_mac_template: &macosx_test_job
  <<: *test_job
  variables:
    <<: *macosx_build_variables


# Template for the wheel uploading stage
# Needs to run against one combination of python 2.x and 3.x if it is a python
# only package, otherwise, needs to run in both pythons to all supported
# architectures (Linux and Mac OSX 64-bit)
.wheels_template: &wheels_job
  stage: wheels
  only:
    - master
    - tags
  before_script:
    - ./bootstrap-conda.sh ${CONDA_FOLDER} ${PYTHON_VER} ${CONDA_PREFIX}
    - ./bin/buildout -o
    - wget -O- https://gitlab.idiap.ch/bob/bob/snippets/8/raw | tr -d '\r' > upload-wheel.sh
    - chmod 755 upload-wheel.sh
  script:
    - ./upload-wheel.sh
  after_script:
    - rm -rf ${CONDA_PREFIX}


# Template for making wheels on a Linux machine
.wheels_linux_template: &linux_wheels_job
  <<: *wheels_job
  variables:
    <<: *linux_build_variables


# Template for making wheels on a Mac OSX machine
.wheels_mac_template: &macosx_wheels_job
  <<: *wheels_job
  variables:
    <<: *macosx_build_variables


# Template for (latest) documentation upload stage
# Only one real job needs to do this (normally, the latest python on OSX)
.docs_template: &docs_job
  stage: docs
  only:
    - master
  before_script:
    - wget -O- https://gitlab.idiap.ch/bob/bob/snippets/9/raw | tr -d '\r' > upload-sphinx.sh
    - chmod 755 upload-sphinx.sh
  script:
    - ./upload-sphinx.sh


# Template for uploading docs on a Linux machine
.docs_linux_template: &linux_docs_job
  <<: *docs_job
  variables:
    <<: *linux_build_variables


# Template for uploading docs on a Mac OSX machine
.docs_mac_template: &macosx_docs_job
  <<: *docs_job
  variables:
    <<: *macosx_build_variables


# 2) Package specific instructions (you may tune this if needed)
# --------------------------------------------------------------

# Linux + Python 2.7: Builds and tests
build_linux_27:
  <<: *linux_build_job
  variables: &linux_27_build_variables
    <<: *linux_build_variables
    PYTHON_VER: "2.7"
  tags:
    - conda-linux

test_linux_27:
  <<: *linux_test_job
  variables: *linux_27_build_variables
  dependencies:
    - build_linux_27
  tags:
    - conda-linux

wheels_linux_27:
  <<: *linux_wheels_job
  variables:
    <<: *linux_27_build_variables
    BOB_WHEEL_TAG: "py27"
  dependencies:
    - build_linux_27
  tags:
    - conda-linux


# Linux + Python 3.4: Builds and tests
build_linux_34:
  <<: *linux_build_job
  variables: &linux_34_build_variables
    <<: *linux_build_variables
    PYTHON_VER: "3.4"
  tags:
    - conda-linux

test_linux_34:
  <<: *linux_test_job
  variables: *linux_34_build_variables
  dependencies:
    - build_linux_34
  tags:
    - conda-linux


# Linux + Python 3.5: Builds and tests
build_linux_35:
  <<: *linux_build_job
  variables: &linux_35_build_variables
    <<: *linux_build_variables
    PYTHON_VER: "3.5"
  tags:
    - conda-linux

test_linux_35:
  <<: *linux_test_job
  variables: *linux_35_build_variables
  dependencies:
    - build_linux_35
  tags:
    - conda-linux

wheels_linux_35:
  <<: *linux_wheels_job
  variables:
    <<: *linux_35_build_variables
    BOB_WHEEL_TAG: "py3"
  dependencies:
    - build_linux_35
  tags:
    - conda-linux

docs_linux_35:
  <<: *linux_docs_job
  dependencies:
    - build_linux_35
  tags:
    - conda-linux


# Mac OSX + Python 2.7: Builds, tests and uploads the wheel
build_macosx_27:
  <<: *macosx_build_job
  variables: &macosx_27_build_variables
    <<: *macosx_build_variables
    PYTHON_VER: "2.7"
  tags:
    - conda-macosx

test_macosx_27:
  <<: *macosx_test_job
  variables: *macosx_27_build_variables
  dependencies:
    - build_macosx_27
  tags:
    - conda-macosx


# Mac OSX + Python 3.4: Builds and tests
build_macosx_34:
  <<: *macosx_build_job
  variables: &macosx_34_build_variables
    <<: *macosx_build_variables
    PYTHON_VER: "3.4"
  tags:
    - conda-macosx

test_macosx_34:
  <<: *macosx_test_job
  variables: *macosx_34_build_variables
  dependencies:
    - build_macosx_34
  tags:
    - conda-macosx


# Mac OSX + Python 3.5: Builds, tests, uploads the wheel and the latest docs
build_macosx_35:
  <<: *macosx_build_job
  variables: &macosx_35_build_variables
    <<: *macosx_build_variables
    PYTHON_VER: "3.5"
  tags:
    - conda-macosx

test_macosx_35:
  <<: *macosx_test_job
  variables: *macosx_35_build_variables
  dependencies:
    - build_macosx_35
  tags:
    - conda-macosx
